### ISSUE TITLE
对swift性能的疑虑

### ISSUE THREAD

**Issue by birneysky** [liuyubobobo/Play-with-Algorithms#1]
我使用swift实现了一个选择排序，发现它的性能比C++实现差了100多倍，是不是swift中Array是值类型的原因？我使用标准库中排序方法(array = array.sorted(by: <)),仅耗时0.013734 s
c++  SelectionSort : 0.116541 s 
swift SelectionSort: 13.858506 s

swift 选择排序的实现:
func selectSort<T:Comparable>(array: inout [T]){
    let n = array.count
    for i in 0 ..< n{
        var minIndex = i
        for j in i ..< n{
            if array[j] < array[minIndex] {
                minIndex = j
            }
        }
        if i != minIndex {
            swap(&array[i], &array[minIndex])
        }
    }
}

**Comment by liuyubobobo** [comment]
1. 请不要使用Playground，使用Command Line Tools
2. 在release模式下进行性能测试

另：课程答疑相关问题，请在交流群或者慕课网问答中提出。
