### ISSUE TITLE
5.4二分查找树的查找一节的Java源码问题

### ISSUE THREAD

**Issue by HeatDeath** [liuyubobobo/Play-with-Algorithms#12]
在main函数的末尾，
` if( i < N )
                assert res == Integer.toString(i);
            else
                assert res == null;`
是不是应该改成
` if( i < N )
                assert res.equals(Integer.toString(i));
            else
                assert res.equals(null);`
更合适一些呢？

**Comment by liuyubobobo** [comment]
谢谢你的提醒，你说得对，String对值判断应该用equals。代码仓中已经进行了修正。不过对null做判断需要使用==哦，不然会报空指针异常：）
