### ISSUE TITLE
C++生成随机数

### ISSUE THREAD

**Issue by jasonlbw** [liuyubobobo/Play-with-Algorithms#14]
1.  0 <= rand() < RAND_MAX
2.  0 <= rand() % (rangR -  rangL) < rangR -  rangL
3.  1 <= rand() % (rangR -  rangL + 1) < rangR -  rangL + 1
4.  rangL + 1 <= rand() % (rangR -  rangL + 1) + rangL < rangR + 1
是不是写的有点问题呢？

**Comment by liuyubobobo** [comment]
第3步推导错了。+1在括号里，不在括号外。

3. 0 <= rand() % (rangR - rangL + 1) < rangR - rangL + 1
4. rangL <= rand() % (rangR - rangL + 1) + rangL < rangR + 1
5. rangL <= rand() % (rangR - rangL + 1) + rangL <= rangR

也就是生成的随机数在 [rangeL, rangeR]
