### ISSUE TITLE
最大堆的插入自动扩展容量补充

### ISSUE THREAD

**Issue by 2165998** [liuyubobobo/Play-with-Algorithms#15]
老师看看O不OK？
```
//往堆中添加一个元素
	public void insert(Item item){
		if(count+1 >= capacity){
			int newCapacity = 1;
			if(capacity <= 1)
				newCapacity = 2;
			else
				newCapacity = capacity + (capacity>>1);
			data = Arrays.copyOf(data, newCapacity);
			capacity = newCapacity;
		}
		data[count+1] = item;
		count++;
		shiftUp(count);
	}
```

**Comment by liuyubobobo** [comment]
非常ok：）其实每次扩容量是原先的2倍就好。另外，考虑到扩容，就可以在减少元素的时候考虑减少空间。不过这里还有一个“复杂度震荡”的问题，具体可以参考我的另一个课程《玩转算法面试》中，以动态数组为例讨论的相关“动态增容和减容”的代码思路：）

https://github.com/liuyubobobo/Play-with-Algorithm-Interview/blob/master/02-Time-Complexity/Course%20Code%20(C%2B%2B)/Optional-1-Dynamic-Vector/MyVector.h
