### ISSUE TITLE
二分搜索树的查找后继的函数似乎有点问题（##后面的函数，应该是调用successorFromAncestor()）

### ISSUE THREAD

**Issue by jincheng00000** [liuyubobobo/Play-with-Algorithms#16]
`// 在以node为根的二叉搜索树中, 寻找key的祖先中,比key大的最小值所在节点, 递归算法
    // 算法调用前已保证key存在在以node为根的二叉树中
    Node* successorFromAncestor(Node* node, Key key){

        if(node->key == key)
            return NULL;

        if(key > node->key)
            // 如果当前节点小于key, 则当前节点不可能是比key大的最小值
            // 向下搜索到的结果直接返回
            return successorFromAncestor(node->right, key);
        else{
            assert(key < node->key);
            // 如果当前节点大于key, 则当前节点有可能是比key大的最小值
            // 向左继续搜索, 将结果存储到tempNode中
            Node* tempNode = ## predecessorFromAncestor(node->left, key);
            if(tempNode)
                return tempNode;
            else
                // 如果tempNode为空, 则当前节点即为结果
                return node;
        }
    }`

**Comment by liuyubobobo** [comment]
你是对的，这里我写错了。我已经进行了修改。谢谢你的提醒：）有兴趣可以加我的微信：liuyubobobo，我会发给你一个小红包：）
