### ISSUE TITLE
ifstream file(filename); 这里file好像创建不成功

### ISSUE THREAD

**Issue by kakukeme** [liuyubobobo/Play-with-Algorithms#2]
macOS 10.12.1下，CLion2016.3.5；图中，ReadGraph读取文件内容；ifstream file(filename); 这里file好像创建不成功，文件打开也是失败的；是因为路径的问题吗....

**Comment by kakukeme** [comment]
解决了，的确是路径问题，参考http://www.jianshu.com/p/8fa53bc691e9

**Comment by liuyubobobo** [comment]
赞！

**Comment by liuyubobobo** [comment]
赞！
