### ISSUE TITLE
LinkedList的add和pop方法不能实现队列的效果

### ISSUE THREAD

**Issue by AllenMRbai** [liuyubobobo/Play-with-Algorithms#22]
Play-with-Algorithms/07-Graph-Basics/Course Code (Java)/Chapter-07-Completed-Code/src/bobo/algo/ShortestPath.java   这个文件的34行创建了一个LinkedList，作为队列使用。但是add和pop方法不能实现队列的效果，应该是使用add和poll。

**Comment by liuyubobobo** [comment]
谢谢。这个问题在最新版的代码中已经修改了，同时q的类型改为Queue而非LinkedList，避免出现这种问题：）最新代码：https://github.com/liuyubobobo/Play-with-Algorithms/blob/master/07-Graph-Basics/Course%20Code%20(Java)/07-BFS-and-Shortest-Path/src/bobo/algo/ShortestPath.java
