### ISSUE TITLE
快速排序的2个问题

### ISSUE THREAD

**Issue by banli17** [liuyubobobo/Play-with-Algorithms#25]
老师讲的快速排序最后一个优化：即大小接近的数据，采用 partition2 

这个应该可以直接用下面2个方法：
1. 采用 partition 1，如果是 =v 的数，随机分配到左右 2边
2. 采用partition 2，下面的代码，应该直接可以 arr[i]<=v，加上了 = 号，而不用像老师那样用 <
```
while(i <=r && arr[i] <= v ) i++
while(j >= l+1 && arr[j] >= v) j--
```

**Comment by liuyubobobo** [comment]
加上=号有问题，请在问答区留言获取更多详情。
