### ISSUE TITLE
5.8节二分搜索树remove操作部分代码优化

### ISSUE THREAD

**Issue by LIUXINJIANG** [liuyubobobo/Play-with-Algorithms#28]
Hi，刘老师！关于**5-8**节二分搜索树的remove操作，在左右两个子节点都存在的情况下，删除该节点，貌似有一种更合理的方式。

- 您的代码：

	Node* successor = new Node(minimum(node->right));
				count++;
				successor->right = removeMin(node->right);
				successor->left = node->left;
				delete node;
				count--;
				return successor;

- 我的代码：
Node* minNodeInRightChildTree = minimum(node->right); //找到替代节点
				//用替代节点的属性覆盖node，起到更新node节点的作用
				node->key = minNodeInRightChildTree->key; 
				node->value = minNodeInRightChildTree->value;
				node->right = removeMin(node->right);
				return node; //将该节点返回

- 性能分析：
我的代码不需要新建Node，也不需要delete过程。比起你的代码，
1. 少了一次动态空间的分配和释放
2. 少了count一加一减过程
3. 少了左节点指针left的复制
4. 多了key和value的单独复制
综上，在批量remove的场景下，我的代码性能也许更优。

班门弄斧，请多指教@…@

**Comment by liuyubobobo** [comment]
赞！没有问题。课程中为了让大家多体会对指针的操作，不采用改变节点值的实现方式：）

**Comment by LIUXINJIANG** [comment]
服！回复速度感人，谢谢刘老师！
