### ISSUE TITLE
bug- binary-search-tree ： levelOrder

### ISSUE THREAD

**Issue by changyubiao** [liuyubobobo/Play-with-Algorithms#33]
06-Binary-Search-Tree-Traverse 中 levelorder 没有对空树 进行检验 ，会出现 空指针异常的情况。如果是空树 ，直接返回就行了。 

pr 我提了一下 ：

https://github.com/liuyubobobo/Play-with-Algorithms/pull/32

**Comment by liuyubobobo** [comment]
非常感谢：）
