### ISSUE TITLE
为什么在头文件中实现函数

### ISSUE THREAD

**Issue by XiaoJiNu** [liuyubobobo/Play-with-Algorithms#35]
您好，我是个c++小白，想请教两个问题。
1 为什么要在头文件中实现函数，为什么不分成.h文件和.cpp文件呢？
2在图这一章中您在SparseGraph.h中的class SparseGraph里面又实现了adjIterator类，我以前没有接触过这种写法，请问您是基于什么考虑要这么写呢？

**Comment by anvalue** [comment]
because of love

**Comment by liuyubobobo** [comment]
1）
C++ 11 之前，C++ 的模板类，.h 和 .cpp 文件不能直接分离，只能写在一起。C++ 11 之后，可以使用 extern 新特性，但这在这个课程中不涉及；

2）
如果你是指为什么使用迭代器，迭代器是一种很常用的设计方式，可以搜索“迭代器”了解更多；
如果你是指为什么使用内部类，因为1）无需向用户暴露这个迭代器接口；2）这个类依附于 SparseGraph；
当然，如果你认为在你的环境中有必要把这个类设计在外面，没有问题，设计模式没有绝对的正误。
