### ISSUE TITLE
Play-with-Algorithms/02-Sorting-Basic/Course Code (C++)/06-Insertion-Sort-Advance/main.cpp

### ISSUE THREAD

**Issue by Hardold** [liuyubobobo/Play-with-Algorithms#6]
void insertionSort(T arr[], int n){

    for( int i = 1 ; i < n ; i ++ ) {

        // 寻找元素arr[i]合适的插入位置
        // 写法1
//        for( int j = i ; j > 0 ; j-- )
//            if( arr[j] < arr[j-1] )
//                swap( arr[j] , arr[j-1] );
//            else
//                break;

        // 写法2
//        for( int j = i ; j > 0 && arr[j] < arr[j-1] ; j -- )
//            swap( arr[j] , arr[j-1] );

        // 写法3
        T e = arr[i];
        int j; // j保存元素e应该插入的位置
        for (j = i; j > 0 && arr[j-1] > e; j--)
            arr[j] = arr[j-1];
        arr[j] = e;
    }

    return;
}

这段代码有错吧？
每次循环完，j都是等于0，e永远插在0的位置

**Comment by liuyubobobo** [comment]
没有问题的哦，请实际运行一下哦：）
