### ISSUE TITLE
代码结构问题

### ISSUE THREAD

**Issue by jimmie0204** [liuyubobobo/Play-with-Algorithms#8]
希望能把java和c++的代码分开整理两个项目中，现在的结构导入到IDE中非常不便，感谢~

**Comment by Mickey-Wang** [comment]
我认为这个还是不同开发领域的同学各取所需自己整理吧，因为波波老师这个项目是以课程章节的结构整体统筹规划的，以后可能还会扩充js、pyson、php...版本的算法，总不能每一种语言建一个项目吧，结构太松散了。我就是自己整理的java版，同时自己还能过一遍，发现问题，解决问题。

**Comment by liuyubobobo** [comment]
谢谢你的建议，我再仔细思考一下。暂时对于只需要C++或者Java版本代码的同学，还请麻烦手动根据自己的需要整理一下相关文件夹。：）

**Comment by doutzenshum** [comment]
亲爱的波波老师，把整个project或者module直接share到GitHub不就可以啦？~~同学们也省去了自己整理的时间哈哈哈
